# Generated by Django 3.2.20 on 2023-08-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bozorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TTZ bozori', max_length=90)),
                ('build_in', models.DateField(default='12-02-2012')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineDokonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('who_created', models.CharField(default='nomalum ', max_length=100)),
                ('when_created', models.DateField(default='10-02-2020')),
            ],
        ),
    ]
